baseURL = 'https://ran-n.github.io/minecraft_info/'
languageCode = 'en'
title = 'Minecraft Information'
theme = 'hugo-theme-monochrome'
defaultContentLanguage = "gz"
enableEmoji = true
#contentDir = 'content'

[build]
writeStats = true
