baseURL = 'https://ran-n.github.io/minecraft_info/'
languageCode = 'en'
title = 'Minecraft Information'
theme = 'hugo-theme-monochrome'
defaultContentLanguage = "gz"
enableEmoji = true
#contentDir = 'content'
custom_js = ["js/custom.js"]
relativeURLs = true
canonifyURLs = true

[build]
writeStats = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
