navbarTitle = "Minecraft Information"
footer = "Minecraft ❤️"

enableZoomingJS = true
enableTOC = true
enableSiteSearch = true
enableMathJax = false

# Codeblock
usePrismJs = false
enablePrismJsLineNo = true
enableCodeCopy = true

#SEO
enableOpenGraph = true
enableTwitterCards = true
author = "Ran#"

# Collapsible Menu
enableCollapsibleTOC = true
enableCollapsibleChangelogs= true
