#navbarTitle = "Minecraft Information 2"
footer = "Minecraft ❤️"

enableZoomingJS = true
enableTOC = true
enableSiteSearch = true
enableMathJax = false

# Codeblock
usePrismJs = false
enablePrismJsLineNo = true
enableCodeCopy = true

#SEO
enableOpenGraph = false
enableTwitterCards = false
author = "Ran#"

# Collapsible Menu
enableCollapsibleTOC = true
enableCollapsibleChangelogs= true
