tag = "tags"

# versions
## java | bedrock
eqt-version-edicion = "eqt-versions-edicions"

## que version/snapshot é
eqt-j-version= "eqt-j-versions-java"
## a que versión pertence a snapshot
eqt-j-snapshot-version= "eqt-j-snapshots-versions"
## dia dos inocentes |
eqt-j-version-especial= "eqt-j-versions-especiais"

## que version/snapshot é
eqt-b-version = "eqt-b-versions"
## a que versión pertence a snapshot
eqt-b-snapshot-version= "eqt-b-snapshots-versions"
## dia dos inocentes |
eqt-b-version-especial= "eqt-b-versions-especiais"
#   #

# creadores
## nome creador
eqt-creador= "eqt-creadores"
## se xoga en java e/ou bedrock
eqt-creador-edicion = "eqt-creadores-edicions"
## en que linguas fai os vídeos
eqt-creador-lingua = "eqt-creadores-linguas"
## a que nación pertence
eqt-creador-nacion = "eqt-creadores-nacions"
#   #

# granxas
eqt-j-granxa-iron-version = "eqt-j-granxa-iron-versions"
eqt-j-granxa-warped-crimson-version = "eqt-j-granxa-warped-crimson-versions"
eqt-j-granxa-mud-version = "eqt-j-granxa-mud-versions"
eqt-j-granxa-clay-version = "eqt-j-granxa-clay-versions"
#   #
