tag = "tags"

# versions
## java | bedrock
eqt-version-edicion = "eqt-versions-edicions"

## que version/snapshot é
eqt-version-java = "eqt-versions-java"
## a que versión pertence a snapshot
eqt-snapshot-version-java = "eqt-snapshots-versions-java"
## dia dos inocentes |
eqt-version-especial-java = "eqt-versions-especiais-java"

## que version/snapshot é
eqt-version-bedrock = "eqt-versions-bedrock"
## a que versión pertence a snapshot
eqt-snapshot-version-bedrock = "eqt-snapshots-versions-bedrock"
## dia dos inocentes |
eqt-version-especial-bedrock = "eqt-versions-especiais-bedrock"
#   #

# creadores
## nome creador
eqt-creador= "eqt-creadores"
## se xoga en java e/ou bedrock
eqt-creador-edicion = "eqt-creadores-edicions"
## en que linguas fai os vídeos
eqt-creador-lingua = "eqt-creadores-linguas"
## a que nación pertence
eqt-creador-nacion = "eqt-creadores-nacions"
#   #

# granxas
eqt-j-granxa-iron-version = "eqt-j-granxa-iron-versions"
eqt-j-granxa-warped-crimson-version = "eqt-j-granxa-warped-crimson-versions"
eqt-j-granxa-mud-version = "eqt-j-granxa-mud-versions"
eqt-j-granxa-clay-version = "eqt-j-granxa-clay-versions"
#   #
