[[navbar]]
    identifier = "minecraft"
    name = "Minecraft"
    url = "/en/minecraft/"
    weight = 1
    [[navbar]]
        parent = 'minecraft'
        identifier = "versions"
        name = "Versions"
        url = "/en/minecraft/versions/"
        weight = 1
        [[navbar]]
            parent = 'versions'
            identifier = "versions_java"
            name = "Java"
            url = "/en/minecraft/versions/java/"
            weight = 1
            [[navbar]]
                parent = 'versions_java'
                identifier = "cronoloxia"
                name = "Chronology"
                url = "/en/minecraft/versions/java/chronology"
                weight = 1
            [[navbar]]
                parent = 'versions_java'
                identifier = "informacion"
                name = "Information"
                url = "/en/minecraft/versions/java/information"
                weight = 2
        [[navbar]]
            parent = 'versions'
            identifier = "versions_bedrock"
            name = "Bedrock"
            url = "/en/minecraft/versions/bedrock/"
            weight = 2

[[navbar]]
    identifier = "granxas"
    name = "Farms"
    url = "/en/farms/"
    weight = 2
    [[navbar]]
        parent = 'granxas'
        identifier = "granxas_java"
        name = "Java"
        url = "/en/farms/java/"
        weight = 1
    [[navbar]]
        parent = 'granxas'
        identifier = "granxas_bedrock"
        name = "Bedrock"
        url = "/en/farms/bedrock/"
        weight = 2

[[navbar]]
    identifier = "trucos"
    name = "Tricks"
    url = "/en/tricks/"
    weight = 3
    [[navbar]]
        parent = 'trucos'
        identifier = "trucos_java"
        name = "Java"
        url = "/en/tricks/java/"
        weight = 1
    [[navbar]]
        parent = 'trucos'
        identifier = "tricks_bedrock"
        name = "Bedrock"
        url = "/en/tricsk/bedrock/"
        weight = 2

[[navbar]]
    identifier = "ferramentas"
    name = "Tools"
    url = "/en/tools/"
    weight = 4
    [[navbar]]
        parent = 'ferramentas'
        identifier = "ferramentas_java"
        name = "Java"
        url = "/en/tools/java/"
        weight = 1
    [[navbar]]
        parent = 'ferramentas'
        identifier = "ferramentas_bedrock"
        name = "Bedrock"
        url = "/en/tools/bedrock/"
        weight = 2

[[navbar]]
    identifier = "redstone"
    name = "Redstone"
    url = "/en/redstone/"
    weight = 5
    [[navbar]]
        parent = 'redstone'
        identifier = "redstone_java"
        name = "Java"
        url = "/en/redstone/java/"
        weight = 1
    [[navbar]]
        parent = 'redstone'
        identifier = "redstone_bedrock"
        name = "Bedrock"
        url = "/en/redstone/bedrock/"
        weight = 2

[[navbar]]
    identifier = "mods"
    name = "Mods"
    url = "/en/mods/"
    weight = 6
    [[navbar]]
        parent = 'mods'
        identifier = "mods_java"
        name = "Java"
        url = "/en/mods/java/"
        weight = 1
    [[navbar]]
        parent = 'mods'
        identifier = "mods_bedrock"
        name = "Bedrock"
        url = "/en/mods/bedrock/"
        weight = 2

[[navbar]]
    identifier = "community"
    name = "Community"
    url = "/en/community/"
    weight = 7
    [[navbar]]
        parent = 'community'
        identifier = "servidores"
        name = "Servers"
        url = "/en/community/servers/"
        weight = 1
        [[navbar]]
            parent = 'servidores'
            identifier = "servidores_java"
            name = "Java"
            url = "/en/community/servers/java/"
            weight = 1
        [[navbar]]
            parent = 'servidores'
            identifier = "servidores_bedrock"
            name = "Bedrock"
            url = "/en/community/servers/bedrock/"
            weight = 2
    [[navbar]]
        parent = 'community'
        identifier = "creadores"
        name = "Creators"
        url = "/en/community/creators/"
        weight = 2

[[navbar]]
    identifier = "sobre"
    name = "About"
    url = "/en/about/"
    weight = 9
