[[navbar]]
    identifier = 'en_minecraft'
    name = '"Minecraft"'
    url = '/en/minecraft/'
    weight = 1
    [[navbar]]
        parent = 'en_minecraft'
        identifier = 'en_version'
        name = 'Versions'
        url = '/en/minecraft/version/'
        weight = 1
        [[navbar]]
            parent = 'en_version'
            identifier = 'en_version_java'
            name = 'Java'
            url = '/en/minecraft/version/java/'
            weight = 1
            [[navbar]]
                parent = 'en_version_java'
                identifier = 'en_version_java_cronoloxia'
                name = 'Chronology'
                url = '/en/minecraft/version/java/chronology/'
                weight = 1
            [[navbar]]
                parent = 'en_version_java'
                identifier = 'en_version_java_informacion'
                name = 'Information'
                url = '/en/minecraft/version/java/information/'
                weight = 2
        [[navbar]]
            parent = 'en_version'
            identifier = 'en_version_bedrock'
            name = 'Bedrock'
            url = '/en/minecraft/version/bedrock/'
            weight = 2
            [[navbar]]
                parent = 'en_version_bedrock'
                identifier = 'en_version_bedrock_cronoloxia'
                name = 'Chronology'
                url = '/en/minecraft/version/bedrock/chronology/'
                weight = 1
            [[navbar]]
                parent = 'en_version_bedrock'
                identifier = 'en_version_bedrock_informacion'
                name = 'Information'
                url = '/en/minecraft/version/bedrock/information/'
                weight = 2

[[navbar]]
    identifier = 'en_conselho'
    name = 'Tips & Tricks'
    url = '/en/tip/'
    weight = 2
    [[navbar]]
        parent = 'en_conselho'
        identifier = 'en_conselho_java'
        name = 'Java'
        url = '/en/tip/java/'
        weight = 1
    [[navbar]]
        parent = 'en_conselho'
        identifier = 'en_conselho_bedrock'
        name = 'Bedrock'
        url = '/en/tip/bedrock/'
        weight = 2

[[navbar]]
    identifier = 'en_tecnico'
    name = 'Technical Minecraft'
    url = '/en/technical-minecraft/'
    weight = 3
    [[navbar]]
        parent = 'en_tecnico'
        identifier = 'en_tecnico_granxa'
        name = 'Farms'
        url = '/en/technical-minecraft/farm/'
        weight = 1
        [[navbar]]
            parent = 'en_tecnico_granxa'
            identifier = 'en_tecnico_granxa_java'
            name = 'Java'
            url = '/en/technical-minecraft/farm/java/'
            weight = 1
        [[navbar]]
            parent = 'en_tecnico_granxa'
            identifier = 'en_tecnico_granxa_bedrock'
            name = 'Bedrock'
            url = '/en/technical-minecraft/farm/bedrock/'
            weight = 2
    [[navbar]]
        parent = 'en_tecnico'
        identifier = 'en_tecnico_redstone'
        name = 'Redstone'
        url = '/en/technical-minecraft/redstone/'
        weight = 2
        [[navbar]]
            parent = 'en_tecnico_redstone'
            identifier = 'en_tecnico_redstone_java'
            name = 'Java'
            url = '/en/technical-minecraft/redstone/java/'
            weight = 1
        [[navbar]]
            parent = 'en_tecnico_redstone'
            identifier = 'en_tecnico_redstone_bedrock'
            name = 'Bedrock'
            url = '/en/technical-minecraft/redstone/bedrock/'
            weight = 2
    [[navbar]]
        parent = 'en_tecnico'
        identifier = 'en_tecnico_exploit'
        name = 'Exploits'
        url = '/en/technical-minecraft/exploit/'
        weight = 3
        [[navbar]]
            parent = 'en_tecnico_exploit'
            identifier = 'en_tecnico_exploit_java'
            name = 'Java'
            url = '/en/technical-minecraft/exploit/java/'
            weight = 1
        [[navbar]]
            parent = 'en_tecnico_exploit'
            identifier = 'en_tecnico_exploit_bedrock'
            name = 'Bedrock'
            url = '/en/technical-minecraft/exploit/bedrock/'
            weight = 2
    [[navbar]]
        parent = 'en_tecnico'
        identifier = 'en_tecnico_pdc'
        name = 'Proofs of Concept'
        url = '/en/technical-minecraft/pdc/'
        weight = 4
        [[navbar]]
            parent = 'en_tecnico_pdc'
            identifier = 'en_tecnico_pdc_java'
            name = 'Java'
            url = '/en/technical-minecraft/pdc/java/'
            weight = 1
        [[navbar]]
            parent = 'en_tecnico_pdc'
            identifier = 'en_tecnico_pdc_bedrock'
            name = 'Bedrock'
            url = '/en/technical-minecraft/pdc/bedrock/'
            weight = 2

[[navbar]]
    identifier = 'en_construccion'
    name = 'Building'
    url = '/en/building/'
    weight = 4

[[navbar]]
    identifier = 'en_mod'
    name = 'Mods'
    url = '/en/mod/'
    weight = 5
    [[navbar]]
        parent = 'en_mod'
        identifier = 'en_mod_java'
        name = 'Java'
        url = '/en/mod/java/'
        weight = 1
    [[navbar]]
        parent = 'en_mod'
        identifier = 'en_mod_bedrock'
        name = 'Bedrock'
        url = '/en/mod/bedrock/'
        weight = 2

[[navbar]]
    identifier = 'en_ferramenta'
    name = 'Tools'
    url = '/en/tool/'
    weight = 6
    [[navbar]]
        parent = 'en_ferramenta'
        identifier = 'en_ferramenta_java'
        name = 'Java'
        url = '/en/tool/java/'
        weight = 1
    [[navbar]]
        parent = 'en_ferramenta'
        identifier = 'en_ferramenta_bedrock'
        name = 'Bedrock'
        url = '/en/tool/bedrock/'
        weight = 2

[[navbar]]
    identifier = 'en_comunidade'
    name = 'Community'
    url = '/en/community/'
    weight = 7
    [[navbar]]
        parent = 'en_comunidade'
        identifier = 'en_comunidade_creador'
        name = 'Creators'
        url = '/en/community/creator/'
        weight = 1
    [[navbar]]
        parent = 'en_comunidade'
        identifier = 'en_comunidade_serie'
        name = 'Series'
        url = '/en/community/serie/'
        weight = 3
    [[navbar]]
        parent = 'en_comunidade'
        identifier = 'en_comunidade_servidor'
        name = 'Servers'
        url = '/en/community/server/'
        weight = 3
        [[navbar]]
            parent = 'en_comunidade_servidor'
            identifier = 'en_comunidade_servidor_java'
            name = 'Java'
            url = '/en/community/server/java/'
            weight = 1
        [[navbar]]
            parent = 'en_comunidade_servidor'
            identifier = 'en_comunidade_servidor_bedrock'
            name = 'Bedrock'
            url = '/en/community/server/bedrock/'
     [[navbar]]
        parent = 'en_comunidade'
        identifier = 'en_comunidade_mundo'
        name = 'Worlds'
        url = '/en/community/world/'
        weight = 4
     [[navbar]]
        parent = 'en_comunidade'
        identifier = 'en_comunidade_minecrafter'
        name = 'Minecrafter'
        url = '/en/community/minecrafter/'
        weight = 5

[[navbar]]
    identifier = 'en_sobre'
    name = 'About'
    url = '/en/about/'
    weight = 8
