[[navbar]]
    identifier = 'en_minecraft'
    name = 'Minecraft'
    url = '/en/minecraft/'
    weight = 1
    [[navbar]]
        parent = 'en_minecraft'
        identifier = 'en_versions'
        name = 'Versions'
        url = '/en/minecraft/versions/'
        weight = 1
        [[navbar]]
            parent = 'en_versions'
            identifier = 'en_versions_java'
            name = 'Java'
            url = '/en/minecraft/versions/java/'
            weight = 1
            [[navbar]]
                parent = 'en_versions_java'
                identifier = 'en_cronoloxia'
                name = 'Chronology'
                url = '/en/minecraft/versions/java/chronology'
                weight = 1
            [[navbar]]
                parent = 'en_versions_java'
                identifier = 'en_informacion'
                name = 'Information'
                url = '/en/minecraft/versions/java/information'
                weight = 2
        [[navbar]]
            parent = 'en_versions'
            identifier = 'en_versions_bedrock'
            name = 'Bedrock'
            url = '/en/minecraft/versions/bedrock/'
            weight = 2

[[navbar]]
    identifier = 'en_granxas'
    name = 'Farms'
    url = '/en/farms/'
    weight = 2
    [[navbar]]
        parent = 'en_granxas'
        identifier = 'en_granxas_java'
        name = 'Java'
        url = '/en/farms/java/'
        weight = 1
    [[navbar]]
        parent = 'en_granxas'
        identifier = 'en_granxas_bedrock'
        name = 'Bedrock'
        url = '/en/farms/bedrock/'
        weight = 2

[[navbar]]
    identifier = 'en_trucos'
    name = 'Tricks'
    url = '/en/tricks/'
    weight = 3
    [[navbar]]
        parent = 'en_trucos'
        identifier = 'en_trucos_java'
        name = 'Java'
        url = '/en/tricks/java/'
        weight = 1
    [[navbar]]
        parent = 'en_trucos'
        identifier = 'en_tricks_bedrock'
        name = 'Bedrock'
        url = '/en/tricsk/bedrock/'
        weight = 2

[[navbar]]
    identifier = 'en_ferramentas'
    name = 'Tools'
    url = '/en/tools/'
    weight = 4
    [[navbar]]
        parent = 'en_ferramentas'
        identifier = 'en_ferramentas_java'
        name = 'Java'
        url = '/en/tools/java/'
        weight = 1
    [[navbar]]
        parent = 'en_ferramentas'
        identifier = 'en_ferramentas_bedrock'
        name = 'Bedrock'
        url = '/en/tools/bedrock/'
        weight = 2

[[navbar]]
    identifier = 'en_redstone'
    name = 'Redstone'
    url = '/en/redstone/'
    weight = 5
    [[navbar]]
        parent = 'en_redstone'
        identifier = 'en_redstone_java'
        name = 'Java'
        url = '/en/redstone/java/'
        weight = 1
    [[navbar]]
        parent = 'en_redstone'
        identifier = 'en_redstone_bedrock'
        name = 'Bedrock'
        url = '/en/redstone/bedrock/'
        weight = 2

[[navbar]]
    identifier = 'en_mods'
    name = 'Mods'
    url = '/en/mods/'
    weight = 6
    [[navbar]]
        parent = 'en_mods'
        identifier = 'en_mods_java'
        name = 'Java'
        url = '/en/mods/java/'
        weight = 1
    [[navbar]]
        parent = 'en_mods'
        identifier = 'en_mods_bedrock'
        name = 'Bedrock'
        url = '/en/mods/bedrock/'
        weight = 2

[[navbar]]
    identifier = 'en_community'
    name = 'Community'
    url = '/en/community/'
    weight = 7
    [[navbar]]
        parent = 'en_community'
        identifier = 'en_creadores'
        name = 'Creators'
        url = '/en/community/creators/'
        weight = 1
    [[navbar]]
        parent = 'en_community'
        identifier = 'en_series_en'
        name = 'Series'
        url = '/en/community/series/'
        weight = 3
    [[navbar]]
        parent = 'en_community'
        identifier = 'en_servidores'
        name = 'Servers'
        url = '/en/community/servers/'
        weight = 3
        [[navbar]]
            parent = 'en_servidores'
            identifier = 'en_servidores_java'
            name = 'Java'
            url = '/en/community/servers/java/'
            weight = 1
        [[navbar]]
            parent = 'en_servidores'
            identifier = 'en_servidores_bedrock'
            name = 'Bedrock'
            url = '/en/community/servers/bedrock/'
     [[navbar]]
        parent = 'en_community'
        identifier = 'en_worlds'
        name = 'Worlds'
        url = '/en/community/worlds/'
        weight = 4
     [[navbar]]
        parent = 'en_community'
        identifier = 'en_minecrafter_en'
        name = 'Minecrafter'
        url = '/en/community/minecrafter/'
        weight = 5


[[navbar]]
    identifier = 'en_sobre'
    name = 'About'
    url = '/en/about/'
    weight = 9
