name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Composite package.json
        run: hugo mod npm pack

      - name: Setup Dependency
        run: npm install

      - name: Setup public
        run: git worktree add -B gh-pages ./public origin/gh-pages

      - name: Clean public
        run: rm -rf ./public/*

      - name: Build
        run: hugo --minify --environment production -b https://github.com/Ran-n/minecraft_info

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
